### PR TITLE
Small README.md updates

### PR DESCRIPTION
**Pull request by brookslybrand**
Mostly just small typos and some suggestions

### CODE REVIEW

**Comment by brookslybrand** [comment]
One small thing: you put the README in this chapter in the same directory as the `bee-rich` directory, whereas in 5 you put it inside of `bee-rich`. Might want to just be consistent in placement

**Comment by brookslybrand** [comment]
I can't comment on this line unfortunately, so will just quote here:

> We further updated the styling of the component. Previously, we used the className property of Remix's NavLink component for styling. Now, we use the isActive property to style the active/current item differently.

This is a little confusing to me, because it does seem like previously you were using the `isActive` property: https://github.com/PacktPublishing/Full-Stack-Web-Development-with-Remix/blob/main/5-fetching-and-mutating-data/bee-rich/solution/app/components/links.tsx#L89-L96

**Comment by andrelandgraf** [comment]
Thanks for highlighting the inconsistency of the README locations! I moved all BeeRich-specifc READMEs into the bee-rich folders now.

> This is a little confusing to me...

Great catch! I updated the README text to be more precise. I was referring to this code [here](https://github.com/PacktPublishing/Full-Stack-Web-Development-with-Remix/blob/main/6-enhancing-the-user-experience/bee-rich/solution/app/components/links.tsx#L87). We are not using Remix's `isActive` prop anymore, but a custom one!

**Comment by andrelandgraf** [comment]
Thanks for spotting the grammar issues, I merged the PR! 💯

**Comment by brookslybrand** [comment]
> Great catch! I updated the README text to be more precise. I was referring to this code [here](https://github.com/PacktPublishing/Full-Stack-Web-Development-with-Remix/blob/main/6-enhancing-the-user-experience/bee-rich/solution/app/components/links.tsx#L87). We are not using Remix's `isActive` prop anymore, but a custom one!

Ahh okay, that makes a lot of sense, thanks for clarifying!

**Pull request merged**
